# Generated by Django 4.1.7 on 2023-02-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('idAuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parqueadero.auto')),
            ],
        ),
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaIngreso', models.CharField(max_length=5)),
                ('horaSalida', models.CharField(max_length=5)),
                ('idAuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parqueadero.auto')),
                ('idPropietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parqueadero.propietario')),
            ],
        ),
    ]
